#!/bin/sh
#
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 1996-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#
# Modified for Rust implementation: calls Rust binary (beam) instead of erlexec
# This script is designed to be copied to target/otp_root/bin/ by the makefile
#
prog="$0"
progdir=`dirname "${prog}"`
dyn_erl_path="${progdir}/dyn_erl"
if [ ! -f "$dyn_erl_path" ]
then
    dyn_erl_path="${progdir}/dyn_erl"
fi

if [ -f "$dyn_erl_path" ]
then
    dyn_rootdir=`"${dyn_erl_path}" --realpath`
    dyn_rootdir=`dirname "${dyn_rootdir}"`
    dyn_rootdir=`dirname "${dyn_rootdir}"`
else
    dyn_rootdir=""
fi

if [ -z "$ERL_ROOTDIR" ]
then
    # When installed by makefile, ROOTDIR should be the parent of bin/
    # So if this script is in ROOTDIR/bin/erl, ROOTDIR is ../
    ROOTDIR=`cd "${progdir}/.." && pwd`
    if [ "$dyn_rootdir" != "$ROOTDIR" ] && [ "$dyn_rootdir" != "" ]
    then
        # It is likely that the files have been copied or moved
        ROOTDIR="$dyn_rootdir"
    fi
else
    ROOTDIR="$ERL_ROOTDIR"
fi

# For Rust implementation, BINDIR is just ROOTDIR/bin (no arch-specific subdirectory)
BINDIR="$ROOTDIR/bin"
EMU=beam
PROGNAME=`basename "$0"`
export EMU
export ROOTDIR
export BINDIR
export PROGNAME

# Modified: call Rust binary (beam) instead of erlexec
exec "$BINDIR/beam" ${1+"$@"}

