graph TD
    subgraph Foundational["Foundational Layer"]
        MemoryManagement["Memory Management<br/>107 funcs"]
        TermHandling["Term Handling<br/>333 funcs"]
        Maps["Maps<br/>76 funcs"]
    end
    subgraph Core["Core Layer"]
        ProcessManagement["Process Management<br/>45 funcs"]
        CodeManagement["Code Management<br/>246 funcs"]
        Bifs["Bifs<br/>416 funcs"]
        Scheduling["Scheduling<br/>5 funcs"]
    end
    subgraph Service["Service Layer"]
        IoPorts["Io Ports<br/>229 funcs"]
        Distribution["Distribution<br/>91 funcs"]
        TimeManagement["Time Management<br/>124 funcs"]
        DebuggingTracing["Debugging Tracing<br/>70 funcs"]
        EtsTables["Ets Tables<br/>343 funcs"]
    end
    subgraph Integration["Integration Layer"]
        SystemIntegration["System Integration<br/>1992 funcs"]
        Drivers["Drivers<br/>200 funcs"]
        Nifs["Nifs<br/>755 funcs"]
    end
    subgraph Utility["Utility Layer"]
        Utils["Utils<br/>172 funcs"]
    end
    ProcessManagement --> Distribution
    ProcessManagement --> Utils
    ProcessManagement --> SystemIntegration
    ProcessManagement --> IoPorts
    ProcessManagement --> Maps
    ProcessManagement --> EtsTables
    MemoryManagement --> Distribution
    MemoryManagement --> Utils
    MemoryManagement --> SystemIntegration
    MemoryManagement --> IoPorts
    MemoryManagement --> TimeManagement
    MemoryManagement --> Bifs
    MemoryManagement --> Nifs
    MemoryManagement --> EtsTables
    MemoryManagement --> ProcessManagement
    CodeManagement --> Distribution
    CodeManagement --> SystemIntegration
    CodeManagement --> Maps
    CodeManagement --> MemoryManagement
    CodeManagement --> TermHandling
    TermHandling --> IoPorts
    TermHandling --> SystemIntegration
    TermHandling --> Bifs
    TermHandling --> CodeManagement
    TermHandling --> Nifs
    TermHandling --> ProcessManagement
    Bifs --> Distribution
    Bifs --> Utils
    Bifs --> SystemIntegration
    Bifs --> IoPorts
    Bifs --> DebuggingTracing
    Bifs --> Maps
    Bifs --> MemoryManagement
    Bifs --> TermHandling
    Bifs --> EtsTables
    Bifs --> Nifs
    IoPorts --> SystemIntegration
    IoPorts --> Maps
    IoPorts --> Bifs
    IoPorts --> TermHandling
    IoPorts --> Nifs
    IoPorts --> ProcessManagement
    Distribution --> SystemIntegration
    Distribution --> Maps
    Distribution --> Bifs
    Distribution --> TermHandling
    Distribution --> ProcessManagement
    TimeManagement --> Bifs
    TimeManagement --> Nifs
    TimeManagement --> SystemIntegration
    DebuggingTracing --> Utils
    DebuggingTracing --> SystemIntegration
    DebuggingTracing --> Maps
    DebuggingTracing --> Bifs
    DebuggingTracing --> TermHandling
    DebuggingTracing --> Nifs
    DebuggingTracing --> ProcessManagement
    EtsTables --> SystemIntegration
    EtsTables --> Maps
    EtsTables --> Bifs
    EtsTables --> CodeManagement
    EtsTables --> Nifs
    EtsTables --> ProcessManagement
    Maps --> Bifs
    Maps --> SystemIntegration
    Maps --> ProcessManagement
    SystemIntegration --> Distribution
    SystemIntegration --> Utils
    SystemIntegration --> IoPorts
    SystemIntegration --> DebuggingTracing
    SystemIntegration --> TimeManagement
    SystemIntegration --> Maps
    SystemIntegration --> Bifs
    SystemIntegration --> MemoryManagement
    SystemIntegration --> TermHandling
    SystemIntegration --> CodeManagement
    SystemIntegration --> EtsTables
    SystemIntegration --> ProcessManagement
    Drivers --> Bifs
    Nifs --> IoPorts
    Nifs --> Utils
    Nifs --> Maps
    Nifs --> Bifs
    Nifs --> EtsTables
    Nifs --> ProcessManagement
    Utils --> Distribution
    Utils --> IoPorts
    Utils --> SystemIntegration
    Utils --> Maps
    Utils --> Bifs
    Utils --> MemoryManagement
    Utils --> TermHandling
    Utils --> CodeManagement
    Utils --> EtsTables
    Utils --> ProcessManagement