graph TD
    ProcessManagement["Process Management<br/>45 funcs<br/>5 files"]
    MemoryManagement["Memory Management<br/>107 funcs<br/>15 files"]
    CodeManagement["Code Management<br/>246 funcs<br/>58 files"]
    TermHandling["Term Handling<br/>333 funcs<br/>13 files"]
    Bifs["Bifs<br/>416 funcs<br/>16 files"]
    IoPorts["Io Ports<br/>229 funcs<br/>29 files"]
    Distribution["Distribution<br/>91 funcs<br/>3 files"]
    Scheduling["Scheduling<br/>5 funcs<br/>1 files"]
    TimeManagement["Time Management<br/>124 funcs<br/>13 files"]
    DebuggingTracing["Debugging Tracing<br/>70 funcs<br/>11 files"]
    EtsTables["Ets Tables<br/>343 funcs<br/>11 files"]
    Maps["Maps<br/>76 funcs<br/>3 files"]
    SystemIntegration["System Integration<br/>1992 funcs<br/>243 files"]
    Drivers["Drivers<br/>200 funcs<br/>17 files"]
    Nifs["Nifs<br/>755 funcs<br/>26 files"]
    Utils["Utils<br/>172 funcs<br/>20 files"]
    ProcessManagement --> Distribution
    ProcessManagement --> Utils
    ProcessManagement --> SystemIntegration
    ProcessManagement --> IoPorts
    ProcessManagement --> Maps
    ProcessManagement --> Bifs
    ProcessManagement --> EtsTables
    MemoryManagement --> Distribution
    MemoryManagement --> Utils
    MemoryManagement --> SystemIntegration
    MemoryManagement --> IoPorts
    MemoryManagement --> TimeManagement
    MemoryManagement --> Maps
    MemoryManagement --> Bifs
    MemoryManagement --> TermHandling
    MemoryManagement --> Nifs
    MemoryManagement --> EtsTables
    MemoryManagement --> ProcessManagement
    CodeManagement --> Distribution
    CodeManagement --> SystemIntegration
    CodeManagement --> Maps
    CodeManagement --> Bifs
    CodeManagement --> MemoryManagement
    CodeManagement --> TermHandling
    CodeManagement --> ProcessManagement
    TermHandling --> IoPorts
    TermHandling --> SystemIntegration
    TermHandling --> Maps
    TermHandling --> Bifs
    TermHandling --> MemoryManagement
    TermHandling --> CodeManagement
    TermHandling --> Nifs
    TermHandling --> ProcessManagement
    Bifs --> Distribution
    Bifs --> Utils
    Bifs --> SystemIntegration
    Bifs --> IoPorts
    Bifs --> DebuggingTracing
    Bifs --> Maps
    Bifs --> MemoryManagement
    Bifs --> TermHandling
    Bifs --> CodeManagement
    Bifs --> EtsTables
    Bifs --> Nifs
    Bifs --> ProcessManagement
    IoPorts --> Distribution
    IoPorts --> SystemIntegration
    IoPorts --> TimeManagement
    IoPorts --> Maps
    IoPorts --> Bifs
    IoPorts --> TermHandling
    IoPorts --> Nifs
    IoPorts --> EtsTables
    IoPorts --> ProcessManagement
    Distribution --> SystemIntegration
    Distribution --> DebuggingTracing
    Distribution --> Maps
    Distribution --> Bifs
    Distribution --> TermHandling
    Distribution --> ProcessManagement
    Scheduling --> Bifs
    TimeManagement --> Bifs
    TimeManagement --> Nifs
    TimeManagement --> SystemIntegration
    DebuggingTracing --> Distribution
    DebuggingTracing --> Utils
    DebuggingTracing --> SystemIntegration
    DebuggingTracing --> Maps
    DebuggingTracing --> Bifs
    DebuggingTracing --> TermHandling
    DebuggingTracing --> Nifs
    DebuggingTracing --> ProcessManagement
    EtsTables --> SystemIntegration
    EtsTables --> Maps
    EtsTables --> Bifs
    EtsTables --> CodeManagement
    EtsTables --> Nifs
    EtsTables --> ProcessManagement
    Maps --> Bifs
    Maps --> TermHandling
    Maps --> SystemIntegration
    Maps --> ProcessManagement
    SystemIntegration --> Distribution
    SystemIntegration --> Utils
    SystemIntegration --> IoPorts
    SystemIntegration --> DebuggingTracing
    SystemIntegration --> TimeManagement
    SystemIntegration --> Maps
    SystemIntegration --> Bifs
    SystemIntegration --> MemoryManagement
    SystemIntegration --> TermHandling
    SystemIntegration --> CodeManagement
    SystemIntegration --> EtsTables
    SystemIntegration --> Nifs
    SystemIntegration --> Drivers
    SystemIntegration --> ProcessManagement
    Drivers --> Bifs
    Drivers --> Nifs
    Drivers --> SystemIntegration
    Nifs --> IoPorts
    Nifs --> SystemIntegration
    Nifs --> Utils
    Nifs --> Maps
    Nifs --> Bifs
    Nifs --> EtsTables
    Nifs --> ProcessManagement
    Utils --> Distribution
    Utils --> IoPorts
    Utils --> SystemIntegration
    Utils --> Maps
    Utils --> Bifs
    Utils --> MemoryManagement
    Utils --> TermHandling
    Utils --> CodeManagement
    Utils --> EtsTables
    Utils --> ProcessManagement