graph TD
    ProcessManagement["Process Management<br/>45 funcs<br/>5 files"]
    MemoryManagement["Memory Management<br/>107 funcs<br/>15 files"]
    CodeManagement["Code Management<br/>246 funcs<br/>58 files"]
    TermHandling["Term Handling<br/>333 funcs<br/>13 files"]
    Bifs["Bifs<br/>416 funcs<br/>16 files"]
    IoPorts["Io Ports<br/>229 funcs<br/>29 files"]
    Distribution["Distribution<br/>91 funcs<br/>3 files"]
    Scheduling["Scheduling<br/>5 funcs<br/>1 files"]
    TimeManagement["Time Management<br/>124 funcs<br/>13 files"]
    DebuggingTracing["Debugging Tracing<br/>70 funcs<br/>11 files"]
    EtsTables["Ets Tables<br/>343 funcs<br/>11 files"]
    Maps["Maps<br/>76 funcs<br/>3 files"]
    SystemIntegration["System Integration<br/>1992 funcs<br/>243 files"]
    Drivers["Drivers<br/>200 funcs<br/>17 files"]
    Nifs["Nifs<br/>755 funcs<br/>26 files"]
    Utils["Utils<br/>172 funcs<br/>20 files"]
    ProcessManagement --> Bifs
    ProcessManagement --> Distribution
    ProcessManagement --> SystemIntegration
    MemoryManagement --> Bifs
    MemoryManagement --> SystemIntegration
    MemoryManagement --> Nifs
    CodeManagement --> Bifs
    CodeManagement --> ProcessManagement
    CodeManagement --> SystemIntegration
    TermHandling --> ProcessManagement
    TermHandling --> Bifs
    TermHandling --> Maps
    TermHandling --> SystemIntegration
    Bifs --> IoPorts
    Bifs --> Distribution
    Bifs --> Maps
    Bifs --> EtsTables
    Bifs --> CodeManagement
    Bifs --> SystemIntegration
    Bifs --> ProcessManagement
    Bifs --> TermHandling
    Bifs --> MemoryManagement
    IoPorts --> Distribution
    IoPorts --> Bifs
    IoPorts --> SystemIntegration
    IoPorts --> ProcessManagement
    IoPorts --> TermHandling
    IoPorts --> Nifs
    Distribution --> Bifs
    Distribution --> SystemIntegration
    TimeManagement --> Nifs
    TimeManagement --> Bifs
    TimeManagement --> SystemIntegration
    DebuggingTracing --> Bifs
    DebuggingTracing --> Maps
    DebuggingTracing --> SystemIntegration
    DebuggingTracing --> ProcessManagement
    DebuggingTracing --> Nifs
    EtsTables --> Nifs
    EtsTables --> ProcessManagement
    EtsTables --> Bifs
    EtsTables --> SystemIntegration
    Maps --> Bifs
    SystemIntegration --> Utils
    SystemIntegration --> IoPorts
    SystemIntegration --> Bifs
    SystemIntegration --> Distribution
    SystemIntegration --> Maps
    SystemIntegration --> EtsTables
    SystemIntegration --> DebuggingTracing
    SystemIntegration --> Nifs
    SystemIntegration --> CodeManagement
    SystemIntegration --> ProcessManagement
    SystemIntegration --> TermHandling
    SystemIntegration --> MemoryManagement
    Drivers --> Bifs
    Drivers --> SystemIntegration
    Nifs --> Bifs
    Nifs --> EtsTables
    Nifs --> SystemIntegration
    Utils --> ProcessManagement
    Utils --> Bifs
    Utils --> SystemIntegration